version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - aws s3 cp s3://myrewardcore.repo/myreward-aws-settings/settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/MyRewardEngineWebApp-0.0.1-SNAPSHOT.war